name: CImGuizmo Build

on: 
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
    
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Install Dependencies
        shell: bash
        env:
          GITHUB_OS: ${{ matrix.os }}
        run: |
          if [ "$GITHUB_OS" == "macOS-latest" ];
          then
            brew install luajit
          elif [ "$GITHUB_OS" == "ubuntu-latest" ];
          then
            sudo apt-get install -y luajit
          elif [ "$GITHUB_OS" == "windows-latest" ];
          then
            vcpkg install luajit:x64-windows
            echo "/C/vcpkg/installed/x64-windows/tools/luajit" >> $GITHUB_PATH
            echo "/C/vcpkg/installed/x64-windows/bin"   >> $GITHUB_PATH
          fi
  
      - name: Download Submodules
        run: |
          git submodule update --init --recursive

      - name: Download Latest CImGui
        shell: bash
        run: |
          git clone https://github.com/psydack/cimgui.git cimgui
  
      - name: Generate Bindings
        shell: bash
        run: |
          cd ./cimguizmo/generator
          bash ./generator.sh

      - run: echo "🍏 This job's status is ${{ job.status }}."
